### ISSUE TITLE
为什么我的识别正确率比你的差好远

### ISSUE THREAD

**Issue by simpsonyang** [equationl/paddleocr4android#10]
我直接运行，识别效果和你的差好远，这是什么原因？
![Screenshot_2022-10-19-16-10-39-881_com equationl paddleocr4android app](https://user-images.githubusercontent.com/30676253/196634495-0034f3be-f018-477b-b896-78186e94ceec.jpg)
另外，我看paddle ocr现在有v3模型了，但是我下载模型文件运行报错，就是你提到的问题6，我下载了paddle lite2.11 的so文件替换了跑不起来，请问具体要怎么做呢？

**Comment by equationl** [comment]
V3 模型现在用不了，识别率取决于模型

**Comment by simpsonyang** [comment]
> V3 模型现在用不了，识别率取决于模型

我是直接运行你的代码，同一个模型啊，为啥结果差异这么大？

**Comment by equationl** [comment]
> > V3 模型现在用不了，识别率取决于模型
> 
> 我是直接运行你的代码，同一个模型啊，为啥结果差异这么大？

这你就问到我了……

**Comment by equationl** [comment]
参考：https://github.com/equationl/paddleocr4android#%E6%B3%A8%E6%84%8F
