### ISSUE TITLE
1.1.1 无法使用同步初始化和同步识别

### ISSUE THREAD

**Issue by Zhao-Dream** [equationl/paddleocr4android#11]
1.1.1 无法使用同步初始化和同步识别
![屏幕截图 2022-11-24 104412](https://user-images.githubusercontent.com/43934172/203682543-673977d5-3949-40df-b3e2-3054d4de953f.jpeg)

**Comment by Zhao-Dream** [comment]
![屏幕截图 2022-11-24 104412](https://user-images.githubusercontent.com/43934172/203682623-49685c7a-4c96-4419-b362-9cebb6ac615b.jpeg)

**Comment by equationl** [comment]
试试看使用kt？
