### ISSUE TITLE
催更啦

### ISSUE THREAD

**Issue by kuisec** [equationl/paddleocr4android#12]
很抱歉打扰一下您，目前Paddle Lite已经更新到了2.12版本，Paddle OCR的模型也更新到了v3，很多像俺这样的安卓程序员不会C++，跪求作者更新！！！

**Comment by equationl** [comment]
抱歉，最近比较忙，有空了我更一下，欢迎各位大佬更新后提交 PR

**Comment by equationl** [comment]
参考：https://github.com/equationl/paddleocr4android#%E6%B3%A8%E6%84%8F
