### ISSUE TITLE
识别速度在不同线程表现

### ISSUE THREAD

**Issue by o2o-Dart** [equationl/paddleocr4android#14]
你好作者我想问下关于识别速度为什么差别很大，在HandlerThread里使用 设置的 Process.THREAD_PRIORITY_URGENT_AUDIO 最高权限
在识别空白图片时很快到了有文字图片就变很慢,但是在OnChecke里面又稍微快一点，这个是什么问题导致呢

**Comment by equationl** [comment]
这个你去 paddlelite 或者 paddleOCR 的仓库下提 issue问问
