### ISSUE TITLE
期待作者的v3版本 封装真的对新手太友好了，十分感谢

### ISSUE THREAD

**Issue by o2o-Dart** [equationl/paddleocr4android#15]

**Comment by equationl** [comment]
已更新：https://github.com/equationl/paddleocr4android/blob/master/doc/fastdeploy.md

**Comment by equationl** [comment]
@liudapang000 已支持

**Comment by liudapang000** [comment]
> @liudapang000 已支持

我在引入implementation 'com.github.equationl.paddleocr4android:fastdeplyocr:v1.2.6'到我自己的项目中，出现了 Resource and asset merger: Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>'请问如何解决，降低了'com.google.android.material:material:1.6.0'版本和implementation 'androidx.appcompat:appcompat:1.4.1'都没有作用

**Comment by equationl** [comment]
> > @liudapang000 已支持
> 
> 我在引入implementation 'com.github.equationl.paddleocr4android:fastdeplyocr:v1.2.6'到我自己的项目中，出现了 Resource and asset merger: Can't determine type for tag '?attr/shapeAppearanceCornerSmall'请问如何解决，降低了'com.google.android.material:material:1.6.0'版本和implementation 'androidx.appcompat:appcompat:1.4.1'都没有作用

依赖冲突了，有空我改一下，实际上这个库并没有用到这些依赖，直接删了就行了

**Comment by liudapang000** [comment]
> > > @liudapang000 已支持
> > 
> > 
> > 我在引入implementation 'com.github.equationl.paddleocr4android:fastdeplyocr:v1.2.6'到我自己的项目中，出现了 Resource and asset merger: Can't determine type for tag '?attr/shapeAppearanceCornerSmall'请问如何解决，降低了'com.google.android.material:material:1.6.0'版本和implementation 'androidx.appcompat:appcompat:1.4.1'都没有作用
> 
> 依赖冲突了，有空我改一下，实际上这个库并没有用到这些依赖，直接删了就行了

我不知道和你哪个依赖产生冲突，我的报错和https://stackoverflow.com/questions/75283152/getting-cant-determine-type-for-tag-macro-name-m3-comp-assist-chip-containe这上面一致，但是按照他的方法修改没有作用

**Comment by equationl** [comment]
删除 https://github.com/equationl/paddleocr4android/blob/master/fastdeployOCR/build.gradle 中的这两个依赖就行了：

```
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
```

**Comment by liudapang000** [comment]
> 删除 https://github.com/equationl/paddleocr4android/blob/master/fastdeployOCR/build.gradle 中的这两个依赖就行了：
> 
> ```
>     implementation 'androidx.appcompat:appcompat:1.6.1'
>     implementation 'com.google.android.material:material:1.9.0'
> ```

期待您的修改！

**Comment by liudapang000** [comment]
> 删除 https://github.com/equationl/paddleocr4android/blob/master/fastdeployOCR/build.gradle 中的这两个依赖就行了：
> 
> ```
>     implementation 'androidx.appcompat:appcompat:1.6.1'
>     implementation 'com.google.android.material:material:1.9.0'
> ```

降低了'com.google.android.material:material:1.6.0'版本和implementation 'androidx.appcompat:appcompat:1.4.1'这句话是我根据网上修改的，并不是报错直接产生的，所以我不知道和你的哪个依赖产生了冲突

**Comment by equationl** [comment]
```
Resource and asset merger: Can't determine type for tag '?attr/shapeAppearanceCornerSmall'
```


你这个报错是因为 material 库版本冲突导致的，但是实际上我这个库并没有用到 material，但是新建项目时 Android Studio 默认把这个依赖加到了 build.gradle 中。

所以现在有两个解决方法：

1. 等我有空了把我这个库中的 material  依赖删除后重新发一个版本。
2. 你直接修改你自己项目的 gradle，强制指定 material  使用你自己的版本（不强制指定的话如果有多个引用会默认使用最新版本，显然我引入的版本比你的版本高）

**Comment by liudapang000** [comment]
感谢 已解决这个问题
