### ISSUE TITLE
引入implementation 'com.github.equationl.paddleocr4android:fastdeplyocr:v1.2.5'出错

### ISSUE THREAD

**Issue by liudapang000** [equationl/paddleocr4android#16]
在运行时报错The minCompileSdk (33) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.appcompat:appcompat-resources:1.6.1.，上网查了一下是由于我使用的android-30版本与appcompat-resources:1.6.1冲突，需要降级，我把您的库fork一下，修改了build.gradle中的appcompat版本，当我使用与你相同的方法引入时（implementation 'com.github.liudapang000.paddleocr4android:fastdeplyocr:v1.2.5'liudapang000是我的用户名）却提示Could not find com.github.liudapang000.paddleocr4android:fastdeplyocr:v1.2.5.，为什么就无法找到我创建的库，我需要修改什么地方吗？请指导谢谢！

**Comment by liudapang000** [comment]
我只是将build.gradle中你的用户名改为我自己的了，请问还有什么地方需要设置或修改的吗？

**Comment by equationl** [comment]
如果你只是想自己用的话，不需要打包到 jitpack 。

本地引入依赖即可：`implementation project(":fastdeployOCR")` 。

如果你想打包到 jitpack，建议先了解一下怎么使用 jitpack：https://docs.jitpack.io/

看你的 jitpack 仓库，你并没有编译，当然会  `Could not find `

![image](https://github.com/equationl/paddleocr4android/assets/6501123/ac163320-d20b-48f0-b94a-c601380e1abf)
