### ISSUE TITLE
ch_ppocr_server_v2.0_rec

### ISSUE THREAD

**Issue by desNBA** [equationl/paddleocr4android#18]
你好，我想问一下ch_ppocr_server_v2.0_rec和ch_PP-OCRv3_rec哪个效果更好点。

如果ch_ppocr_server_v2.0_rec更好，请问是否可以配置，我不在乎安装包的大小和速度如何。

**Comment by desNBA** [comment]
emomo,识别效果更差

**Comment by equationl** [comment]
可以使用 V2 的模型，只要在配置文件中把 ppocr 版本改成 V2 就行：

`config.modelVersion = ModelVersion.V2`

但是理论上来说 V3 模型的精度比 V2 高
