### ISSUE TITLE
必须自己在build.gradle里加入ndk的过滤部分，只接受那两种.so，否则就无法初始化唉

### ISSUE THREAD

**Issue by Liu-jian-kang** [equationl/paddleocr4android#2]

**Comment by equationl** [comment]
是的，因为源程序过滤了只支持 `arm64-v8a、armeabi-v7a` 有时间我看看支持其他 abi 不，支持的话我把这个给去掉，不应该在这里做限制的

**Comment by equationl** [comment]
查了一下，官方demo也只支持 arm64-v8a、armeabi-v7a 两种 abi 的 cpu ，但是我看官方有说明可以自己编译其他 abi 的支持。有时间我试试看。
