### ISSUE TITLE
你可以暂时先在你的混淆配置文件中添加：

### ISSUE THREAD

**Issue by desNBA** [equationl/paddleocr4android#22]
你可以暂时先在你的混淆配置文件中添加：

`-keep class com.baidu.paddle.fastdeploy.** { *; }`

_Originally posted by @equationl in https://github.com/equationl/paddleocr4android/issues/21#issuecomment-1576142822_
            

已经搞好了，但是又有个新问题。models里面我看有个文件，

ArchivePathEntry: pathPrefix="", path="/assets/models/ppocr_keys_v1.txt"

这个文件有详细的解释吗？我自定义了一个并ocrConfig.setLabelPath设置了他的路径

但是他好像不能使用

![image](https://user-images.githubusercontent.com/52272581/243275480-d764a98d-1731-4d72-bcf7-38ab96374b66.png)

**Comment by equationl** [comment]
这个文件是模型的字典标签文件，不能自己写的，除非你是自己训练的模型，那么就可以改这个标签文件。

具体可以查看： https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/recognition.md#14-%E5%AD%97%E5%85%B8
