### ISSUE TITLE
識別結果只能顯示一部分

### ISSUE THREAD

**Issue by Whittaker0323** [equationl/paddleocr4android#23]
基於paddle-lite識別：
1.由於頁面限制，一部分識別結果被裁掉了，無法顯示出來，這個怎么解決呢。
2.不知道什麽原因，中文識別的文字，前後兩句話的順序是反的。

**Comment by equationl** [comment]
你好，请问能提供一下截图或者视频吗？

**Comment by equationl** [comment]
长时间未回复，有需要请重新打开
