### ISSUE TITLE
华为nova手机识别失败

### ISSUE THREAD

**Issue by FuXiangGit** [equationl/paddleocr4android#24]
识别失败：java.lang.NullPointerExecption:rawResult.mText must be null

**Comment by equationl** [comment]
能提供一下完整的报错信息吗？

**Comment by FuXiangGit** [comment]
![1687943238560](https://github.com/equationl/paddleocr4android/assets/5907168/43d311b2-c09a-4d85-8721-7f16cf48d6ac)

**Comment by FuXiangGit** [comment]
![image](https://github.com/equationl/paddleocr4android/assets/5907168/faa38af4-622b-4681-a5dc-834d48690b18)
