### ISSUE TITLE
v1.2.8 jitpack failed

### ISSUE THREAD

**Issue by cagnulein** [equationl/paddleocr4android#27]
Hi! Thanks for your hard work, very appreciated!
I would like only to remind that the v1.2.8 on jitpack failed
Check https://jitpack.io/com/github/equationl/paddleocr4android/v1.2.8/build.log
Thanks

**Comment by cagnulein** [comment]
ah thanks @equationl 
yeah i got a similar issue too with the "v" in the version, I didn't investigate it yet neither.

**Comment by cagnulein** [comment]
hi again @equationl , there is something that I can't understand, forgive me if it's sound stupid

The app project of this repo works perfectly, thanks.
Then I tried the fastdeploydemo and it always gives me a nosuchfileeception about the missing model. So which is the purpose of the fastdeploydemo?

Thanks and sorry again for my stupidity

**Comment by equationl** [comment]
@cagnulein  As I said in README, I don't push model file to fastdeploydemo, because it too big, so you need download model to  fastdeploydemo by yourself.

> 因为 Paddle 模型比较大，所以没有集成模型到 demo （[fastdeploydemo](https://github.com/equationl/paddleocr4android/blob/master/fastdeploydemo)）中，如果想要运行 demo，您需要自行下载模型后放入 [./fastdeploydemo/src/main/assets](https://github.com/equationl/paddleocr4android/blob/fastdeploydemo/src/main/assets) 中:

you can download at this link: https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/models_list_en.md

**Comment by cagnulein** [comment]
> As I said in README, I don't push model file to fastdeploydemo, because it too big, so you need download model to fastdeploydemo by yourself.

hah ok sorry, I can't translate the chinese correctly with google so I didn't understand that part.
Thanks for the answer, very appreciated!

**Comment by cagnulein** [comment]
hi @equationl fastdeploydemo now works perfectly! thanks
Could I make another question?
I'm trying to integrate it on my qdomyos-zwift project here on github and I'm currently figthing with this issue

```
08-16 11:59:42.724  7973  7973 E ScreenCaptureService: onFail: 初始化失败
08-16 11:59:42.724  7973  7973 E ScreenCaptureService: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~8vHiyc_xFS8cxp37oHQmXg==/org.cagnulen.qdomyoszwift-Bfj-9-OB43YHBt0-kR9KyA==/lib/arm64/libpaddle_full_api_shared.so"...
08-16 11:59:42.724  7973  7973 E ScreenCaptureService: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
08-16 11:59:42.724  7973  7973 E ScreenCaptureService: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
08-16 11:59:42.724  7973  7973 E ScreenCaptureService: 	at java.lang.System.loadLibrary(System.java:1661)
08-16 11:59:42.724  7973  7973 E ScreenCaptureService: 	at com.baidu.paddle.fastdeploy.FastDeployInitializer.init(FastDeployInitializer.java:19)
08-16 11:59:42.724  7973  7973 E ScreenCaptureService: 	at com.baidu.paddle.fastdeploy.pipeline.PPOCRBase.<clinit>(PPOCRBase.java:176)
08-16 11:59:42.724  7973  7973 E ScreenCaptureService: 	at com.equationl.fastdeployocr.OCR.initModel(OCR.kt:245)
08-16 11:59:42.724  7973  7973 E ScreenCaptureService: 	at com.equationl.fastdeployocr.OCR.initModelSync-IoAF18A(OCR.kt:85)
08-16 11:59:42.724  7973  7973 E ScreenCaptureService: 	at com.equationl.fastdeployocr.OCR$initModel$1.invokeSuspend(OCR.kt:102)
08-16 11:59:42.724  7973  7973 E ScreenCaptureService: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-16 11:59:42.724  7973  7973 E ScreenCaptureService: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-16 11:59:42.724  7973  7973 E ScreenCaptureService: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
08-16 11:59:42.724  7973  7973 E ScreenCaptureService: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
08-16 11:59:42.724  7973  7973 E ScreenCaptureService: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
08-16 11:59:42.724  7973  7973 E ScreenCaptureService: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
08-16 11:59:42.724  7973  7973 E ScreenCaptureService: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
08-16 11:59:42.724  7973  7973 E ScreenCaptureService: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

do you ever seen it?
Thanks!

**Comment by equationl** [comment]
It's seem ndk version problem, try about this:

https://github.com/android/ndk/issues/329

**Comment by cagnulein** [comment]
interesting @equationl your fastdeploydemo works on the android simulator on my mac, but it does the same __emutls_get_address error on my android 14 pixel 6a.

Are you able to test it as well?

**Comment by equationl** [comment]
Sure, I will test it, But I don't have android 14 device, So I just test in simulator

**Comment by cagnulein** [comment]
nevermind @equationl I tried it again and there was a problem on my repository, i missed the libc++ shared.so

**Comment by viclm** [comment]
> nevermind @equationl I tried it again and there was a problem on my repository, i missed the libc++ shared.so

how did u resolved?
