### ISSUE TITLE
config.scoreThreshold 配置无效，det模型仍然会显示所有检测框

### ISSUE THREAD

**Issue by memoryrobber** [equationl/paddleocr4android#29]
如题

**Comment by equationl** [comment]
使用的是 fastDeploy 还是 Paddle-Lite ？

如果是 fastDeploy 的话，这配置实际上是没有使用的，另外即使是 Paddle-Lite ，这个配置表示的也只是识别的 scoreThreshold 而不是检测的 scoreThreshold。

**Comment by equationl** [comment]
长时间未回复，有需要请重新打开
