### ISSUE TITLE
请教一下，README里演示图用的哪些模型？

### ISSUE THREAD

**Issue by akumasign** [equationl/paddleocr4android#30]
请教一下，你README里演示图用的哪些模型？因为我试了所有官方模型组合，用来识别你源码中带的那张图，效果全都没你截图里那么好。最难以置信的是所有det模型都无法像你演示截图里一样把3句话全部完整分成3个部分。

**Comment by equationl** [comment]
就是官方的 v3 slim量化 模型，这个识别效果还却决于运行的设备。

同样的模型和demo，我自测使用 macos 的 arm 模拟器识别效果最佳（就是 README 演示的效果），但是使用真机（mi 10u）效果就不是太理想，就如你所说，甚至检测模型都无法检测正确的文本分段。
