### ISSUE TITLE
关于测试的图片如何更换问题

### ISSUE THREAD

**Issue by fanruifeng** [equationl/paddleocr4android#33]
请教下博主, 我想更换测试照片, 是在哪块进行更改呢,包括更换图片的名字, 批量读取图片进行识别, 或者 实时访问摄像头参数点击拍照进行识别这块的控制程序；

**Comment by equationl** [comment]
详情参考： https://github.com/equationl/paddleocr4android#4%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8

将 bitmap 传入即可，demo 中是通过 `BitmapFactory.decodeResource(resources, R.drawable.test4)` 解码 `Drawable` 中的图片为 bitmap 来识别的。

**Comment by fanruifeng** [comment]
好的, 明白了,谢谢博主
