### ISSUE TITLE
导包之后不能获取到OcrConfig

### ISSUE THREAD

**Issue by Laze1** [equationl/paddleocr4android#37]
`
 implementation("com.github.equationl.paddleocr4android:fastdeplyocr:v1.2.8")
 maven(url = "https://jitpack.io")
`
这两个都添加了
然而并不能获取到OcrConfig，并且一直到版本v1.1.1也不行

**Comment by Laze1** [comment]
v1.2.7可以了

**Comment by equationl** [comment]
嗯，jitpack 不是很好使，老是莫名其妙的构建失败……
