### ISSUE TITLE
请求更新至最新的paddleocr2.5

### ISSUE THREAD

**Issue by luomo0101** [equationl/paddleocr4android#4]
如题，paddleocr已经发布了最新的2.5 release版本，并且paddle light也更新至了2.10，希望可以早日更新上，用之前的2.9 light是不能直接使用最新的2.5的ocr模型的。
万分感谢，这个项目对我帮助非常大！

**Comment by equationl** [comment]
有空我看看改一下，同时也欢迎提PR
