### ISSUE TITLE
咨询个问题，我要下载哪些模型文件才能识别图片呢？

### ISSUE THREAD

**Issue by binbjz** [equationl/paddleocr4android#40]
需要从 https://github.com/equationl/paddleocr4android 下载下面的模型文件，但是这个链接中 这么多模型文件，哪些才是呢。OCR服务需要使用的呢？我只下载 文本检测、文本识别、文本方向分类 的 训练模型就可以吗？

xx_cls.pdmodel
xx_cls.pdiparams
xx_det.pdmodel
xx_det.pdiparams
xx_rec.pdmodel
xx_rec.pdiparams

**Comment by equationl** [comment]
![image](https://github.com/user-attachments/assets/0a9f0022-6da2-46a0-9cf0-50920ef618e7)

是的，总共也就只有这三个模型啊，只是不同版本不同优化的而已啊

**Comment by binbjz** [comment]
已经成功的集成到工程中了，模型加载和识别都成功了。谢谢回复。
