### ISSUE TITLE
OcrResultModel 中的Point  值比实际的值等比例放大了

### ISSUE THREAD

**Issue by tseenola** [equationl/paddleocr4android#47]
您好，经过测试发现在手机中识别到的文字的point 和 实际的坐标不一样，被等比例放大了，目前只测试了一个手机不知道这个比例是不是固定的。
三星s23 测试如下
获取到的     point [Point(1593, 278), Point(1905, 278),  Point(1593, 434)] Point(1905, 434), 
实际的坐标 	   577 102            675 102             577 152            675 152    
实际的坐标约等于 =  point * 0.36

**Comment by equationl** [comment]
你好，可以把你测试用的原图发一下吗？

**Comment by tseenola** [comment]
![原始图片](https://github.com/user-attachments/assets/52eb3d02-aa81-4893-ab34-a9c7bcd5c9f8)
![uiautomator 坐标](https://github.com/user-attachments/assets/91fb0817-83fe-4e31-a156-9e1c748b64a9)

测试后【信息】 的坐标  [Point(1064, 1424), Point(1268, 1424), Point(1268, 1533), Point(1064, 1533)] 信息
实际的坐标 [291,276][537,632]

**Comment by equationl** [comment]
检查一下你解码图片为 bitmap 的方法，并确认一下解码为 bitmap 后，bitmap 的长宽是否与原图长宽一致。

某些解码 bitmap 的方法就是会按照实际屏幕尺寸缩放 bitmap。

我这里测试的结果没有问题。

这是原图中 “信息” 文字的坐标：

![image](https://github.com/user-attachments/assets/316d0cf7-a0fe-4f9b-9827-291e13a1d8f9)

这是实际识别出来的坐标：

![image](https://github.com/user-attachments/assets/cbd9e0b8-a03e-4c6d-baf3-e4d6f58bc8de)
