### ISSUE TITLE
好兄弟，这个库和原来的demo一样，你识别看看你的行程码，会缺少字

### ISSUE THREAD

**Issue by wyk304443164** [equationl/paddleocr4android#9]
但是识别的已经框选出来了。就是不显示出，我现在行程是 江苏省泰州市，江苏省无锡市，泰州市就没了，字典里面有 泰 州 这两个字/(ㄒoㄒ)/~~

**Comment by equationl** [comment]
对的啊，这个就是对demo做的简单封装啊，没有做其他额外处理，所以如果demo识别不出来的，这个也识别不出来……

你可以试试针对性的自训练模型，可能是模型不太行
